#pragma once

typedef enum {
  MQTT_CONNECTED  = 101,
  SHUTTING_DOWN   = 102,
  POWER_ON        = 103,

  OTA_STARTED     = 301,
  OTA_ERROR       = 302,
  OTA_COMPLETE    = 303,
  OTA_VERIFIED    = 304,
  OTA_ROLLBACK    = 305,
  OTA_INCOMPLETE  = 306,

  BLE_CONNECTED   = 401,
  BLE_DISCONNECTED= 402,
  BLE_INIT_FAILURE= 403,
} AlertCode;

#define SEVERITY_DEBUG    "DEBUG"
#define SEVERITY_INFO     "INFO"
#define SEVERITY_WARNING  "WARNING"
#define SEVERITY_ERROR    "ERROR"
#define SEVERITY_CRITICAL "CRITICAL"

#define ALERT_MQTT_CONNECTED   MQTT_CONNECTED, SEVERITY_INFO,    "MQTT Connected"
#define ALERT_SHUTTING_DOWN    SHUTTING_DOWN,  SEVERITY_WARNING, "Shutting Down"
#define ALERT_POWER_ON         POWER_ON,       SEVERITY_INFO,    "Power On"

#define ALERT_OTA_STARTED      OTA_STARTED, SEVERITY_INFO,       "OTA Update Started"
#define ALERT_OTA_ERROR        OTA_ERROR, SEVERITY_ERROR,        "OTA Error"
#define ALERT_OTA_COMPLETE     OTA_COMPLETE, SEVERITY_INFO,      "OTA Update Complete"
#define ALERT_OTA_VERIFIED     OTA_VERIFIED, SEVERITY_INFO,      "OTA Update Verified"
#define ALERT_OTA_ROLLBACK     OTA_ROLLBACK, SEVERITY_CRITICAL,  "OTA Rollback"
#define ALERT_OTA_INCOMPLETE   OTA_INCOMPLETE, SEVERITY_ERROR,   "In-flight OTA did not finish!"

#define ALERT_BLE_CONNECTED    BLE_CONNECTED, SEVERITY_INFO,        "BLE Device Connected"
#define ALERT_BLE_DISCONNECTED BLE_DISCONNECTED, SEVERITY_WARNING,  "BLE Device Disconnected"
#define ALERT_BLE_INIT_FAILURE BLE_INIT_FAILURE, SEVERITY_ERROR,    "BLE Initialization Failure!"
